### ISSUE TITLE
Tracking materials to gather into this text

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/blackpaper#1]
- [ ] https://github.com/RGB-WG/rgb-node/discussions/218
- [ ] https://github.com/RGB-WG/rgb-node/discussions/219
- [ ] https://github.com/RGB-WG/rgb-node/discussions/228
- [ ] https://github.com/RGB-WG/rgb-node/discussions/220
- [ ] https://github.com/orgs/LNP-BP/discussions/132
- [ ] https://github.com/orgs/LNP-BP/discussions/122
- [ ] https://github.com/RGB-WG/contractum.org
- [ ] https://github.com/RGB-WG/rgb-node/discussions/243
- [ ] https://github.com/RGB-WG/contractum-lang/discussions/1
